<?php
/** @var SumkabumData $dataRepository */
/** @var \Sumkabum\Magento2ProductImport\Block\System\Config\Form\ImporterStatus $block */

use Magento\Framework\App\ObjectManager;
use Magento\Framework\Url;
use Sumkabum\Magento2ProductImport\Repository\SumkabumData;
use Sumkabum\Magento2ProductImport\Service\ImporterStatus;
use Sumkabum\Magento2ProductImport\Service\Scheduler;

/** @var Url $url */
$url = ObjectManager::getInstance()->get(\Magento\Framework\UrlInterface::class);
/** @var Scheduler $schedulerService */
$schedulerService = ObjectManager::getInstance()->get(Scheduler::class);
$currentRunningJob = $schedulerService->getCurrentRunningJob($block->getData('job_code'));
if ($currentRunningJob) {
    echo 'Import currently running. Started at ' . $currentRunningJob->getData('executed_at') . ' UTC<br>';
    $dataRepository = ObjectManager::getInstance()->get(SumkabumData::class);
    $progress = $dataRepository->get(ImporterStatus::DATA_KEY_IMPORTER_PROGRESS);
    echo $dataRepository->get(ImporterStatus::DATA_KEY_IMPORTER_CURRENT_JOB) ?><?php echo $progress ? ': ' . (int) $progress . ' %' : '';

} else {

    if ($nextJob = $schedulerService->getNextJob($block->getData('job_code'))) {
        echo 'Scheduled at ' . $nextJob->getData('scheduled_at') . ' UTC';
        $startNowUrl = $url->getUrl('sumkabumimporter/cronJob/scheduleNow', ['job_code' => $block->getData('job_code')]);
        echo ' <button onclick="window.location.href = \'' . $startNowUrl . '\'; return false;">Schedule now</button></td>';
    } else {
        echo 'Next run not found.';
    }
}
